version: '3.8'

services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: max
#      MONGO_INITDB_ROOT_PASSWORD: secret
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
#    build: 
#      context: ./backend
#      dockerfile: Dockerfile
#      args:
#        some-args: 1
    ports:
      - '80:80'
    volumes:
      - logs:/apps/logs
      - /home/shoaib/my-docker-tests/multi-container/backend:/app
      - /app/node_modules 
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - "/home/shoaib/my-docker-tests/multi-container/frontend/src:/app/src"
    stdin_open: true
    tty: true
    depends_on:
      - backend
  
volumes:
  data:
  logs: