FROM node:14-alpine

WORKDIR /app

## only to run npm commands use entry point
ENTRYPOINT [ "npm" ]

# docker build -t node-util .
# docker container run -it -v /mnt/f/Learning/Docker/docker-projects/docker-practical/utility/utility-container:/app node-util npm init
# docker build -t mynpm-util .
# docker container run -it -v /mnt/f/Learning/Docker/docker-projects/docker-practical/utility/utility-container:/app mynpm-util init
# docker container run -it -v /mnt/f/Learning/Docker/docker-projects/docker-practical/utility/utility-container:/app mynpm-util install express --save
# docker compose run npm init
# docker compose run npm install
# https://jtreminio.com/blog/running-docker-containers-as-current-host-user/
# https://vsupalov.com/docker-shared-permissions/
