apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: second-app
spec:
  selector:
   app: second-app
  ports:
    - port: 80
      protocol: 'TCP'
      targetPort: 8080
  type: LoadBalancer